project: 
  type: website
  
website: 
  page-navigation: true
  title: "Intro To R" 
  site-url: "https://martinahyang.github.io/IntroToR_Winter2026/" 
  repo-url: https://github.com/MartinaHYang/IntroToR_Winter2026
  repo-actions: [edit, issue]
  
  page-footer:
    left: "&copy; CC-By Martina, 2026. All rights reserved."
    right: "This page is built with [Quarto](https://quarto.org/)."
    center: "Workshop created as part of the McGill Initiative in Computational Medicine."
    
  sidebar:
    logo: "images/MiCM_logo.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://www.mcgill.ca/micm/
        text: "GLS-MiCM"
      - icon: github
        href: https://github.com/QLS-MiCM
        text: "MiCM Github"     
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - text: "WelcomeğŸ‰"
        href: index.qmd
      - text: "Why R for Data Science?"
        href: WhyR.qmd
      - text: "Installing R and RStudio"
        href: Setup.qmd
      - text: "Get Acquainted with RStudio"
        href: RStudio.qmd
      - section: "ğ‘ ğğ€ğ’ğˆğ‚ğ’"
        contents:
          - text: "Syntax"
            href: RBasics/Syntax.qmd


format:
  html:
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

