project: 
  type: website
  
website: 
  page-navigation: true
  title: "Intro To R" 
  site-url: "https://martinahyang.github.io/IntroToR_Winter2026/" 
  repo-url: https://github.com/MartinaHYang/IntroToR_Winter2026
  repo-actions: [edit, issue]
  
  page-footer:
    left: "&copy; CC-By Martina, 2026. All rights reserved."
    right: "This page is built with [Quarto](https://quarto.org/)."
    center: "Workshop created as part of the McGill Initiative in Computational Medicine."
    
  sidebar:
    logo: "images/MiCM_logo.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://www.mcgill.ca/micm/
        text: "GLS-MiCM"
      - icon: github
        href: https://github.com/QLS-MiCM
        text: "MiCM Github"     
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - text: "WelcomeğŸ‰"
        href: index.qmd
      - text: "QLS-MiCM"
        href: WebsiteCodes/QLS_MiCM.qmd
      - text: "Why R for Data Science?"
        href: WebsiteCodes/WhyR.qmd
      - text: "Installing R and RStudio"
        href: WebsiteCodes/Setup.qmd
      - text: "Get Acquainted with R and RStudio"
        href: WebsiteCodes/RStudio.qmd
      - text: "How to Use This Materials"
        href: WebsiteCodes/MaterialsInstructions.qmd
      - section: "ğ‘ ğğ€ğ’ğˆğ‚ğ’: Data types and data structures"
        contents:
          - text: "Overview"
            href: WebsiteCodes/Overview.qmd
          - text: "ğŸ­ Atomic Classes (Data Types)"
            href: WebsiteCodes/01AtomicClasses.qmd
          - text: "ğŸ® Arithmetic operators"
            href: WebsiteCodes/02ArithmeticOp.qmd
          - text: "ğŸ¯ Syntax operators"
            href: WebsiteCodes/03SyntaxOp.qmd
          - text: "ğŸ° Logical operators"
            href: WebsiteCodes/04LogicalOp.qmd
          - text: "ğŸ± Objects (Data Structures)"
            href: WebsiteCodes/05Objects.qmd  
      - section: "ğ‘ ğğ€ğ’ğˆğ‚ğ’: Control structures and functions"
        contents:
          - text: "Overview"
            href: WebsiteCodes/Overview2.qmd
          - text: "ğŸ² Conditional Statements"
            href: WebsiteCodes/ConditionalStat.qmd
          - text: "ğŸ³ For Loop/While Loop"
            href: WebsiteCodes/Loop.qmd
          - text: "ğŸ´ Create New Functions"
            href: WebsiteCodes/NewFunctions.qmd
          - text: "ğŸµ Packages"
            href: WebsiteCodes/Packages.qmd
      - section: "ğ‘ ğğ€ğ’ğˆğ‚ğ’: Data Manipulation"
        contents:
          - text: "Overview"
            href: WebsiteCodes/Overview3.qmd
          - text: "ğŸ­ğŸ¬ Reading/Writing Data"
            href: WebsiteCodes/RWData.qmd
          - text: "ğŸ­ğŸ­ Exploring Data Frames"
            href: WebsiteCodes/AdvDataFrames.qmd            
          - text: "ğŸ­ğŸ®	Useful Packages for Data Manipulation"
            href: WebsiteCodes/Packages4Data.qmd
      - section: "ğ‘ ğğ€ğ’ğˆğ‚ğ’: Generating Visual Outputs"
        contents:
          - text: "Overview"
            href: WebsiteCodes/Overview4.qmd
          - text: "ğŸ­ğŸ¯ Graphics"
            href: WebsiteCodes/Graphics.qmd
          - text: "ğŸ­ğŸ° Reports with Knitr"
            href: WebsiteCodes/Knitr.qmd
      - text: "Concluding Remarks"
        href: WebsiteCodes/ConcludingRemarks.qmd


format:
  html:
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

